default:
  image: 
    name: openjdk:8-alpine
  before_script:
    # Install the required software/updates
    - apk update
    - apk add git
    - apk add wget
    - apk add busybox
    - rm -rf Vault
  tags:
    # Pick a specific Shared GitLab runner to execute on
    - icboca # Innovation Cloud
    #- us-east # Use either Boca or Alpha
    - docker
    - linux
    - privileged

stages:
    # The order listed here is the order these run inside the pipelines
    - build
    - test
    - documentation
    - publish
    - deploy

include:
  # YML Scripts that interact with GitLab Repositories (Generating Merge Requests, Pushing Commits/Tags, etc)
  - local: 'Automation/Repository.yml'
  # YML Scripts that interact with Documentation Tools (Confluence, GitLab Wiki, etc)
  - local: 'Automation/Documentation.yml'