default:
  image: 
    name: openjdk:8-alpine
  before_script:
    # Install the required software/updates
    - apk update
    - apk add git
    - apk add wget
    - apk add busybox
    - rm -rf Vault
  tags:
    # Pick a specific Shared GitLab runner to execute on
    - icboca # Innovation Cloud
    #- us-east # Use either Boca or Alpha
    - docker
    - linux
    - privileged

stages:
    # The order listed here is the order these run inside the pipelines
    - build
    - test
    - documentation
    - publish
    - deploy

include:
  # Generate a new GitLab Tag
  - local: 'Automation/Repository/tagCreation.yml'
  # Update our KEL Code Documentation - Finds .kel files in various GitLab Projects
  - local: 'Automation/Documentation/KELProjects.yml'