default:
  image: 
    name: gitlab.ins.risk.regn.net:4567/risk-engineering/vault/openjdk:14-alpine # OpenJDK 14
  before_script:
    # Install the required software/updates
    - apk update --allow-untrusted --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main/
    - apk add --upgrade apk-tools --allow-untrusted --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main/
    - apk upgrade --available --allow-untrusted --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main/
    - apk add --allow-untrusted git --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main/
    - apk add --allow-untrusted git-lfs --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/community/
    - apk add --allow-untrusted wget --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main/
    - apk add --allow-untrusted busybox --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main/
    - apk add --allow-untrusted coreutils --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main/
    - apk add --allow-untrusted curl --repository http://dl-cdn.alpinelinux.org/alpine/v3.15/main/
    - rm -rf KnowledgeUniverse
  tags:
    # Pick a specific Shared GitLab runner to execute on
    - icboca # Innovation Cloud
    #- us-east # Use either Boca or Alpha
    - docker
    - linux
    - privileged

stages:
    # The order listed here is the order these run inside the pipelines
    - build # Generic build stage
    - merge # Code Merge
    - test # Generic test stage
    - thor_test # Test code on Thor, doesn't need to wait for a Publish step to test
    - publish # Push code to Roxie
    - deploy # Generic deploy stage
    - roxie_test # Test code on Roxie
    - documentation # Generate or update Documentation

include:
  # YML Scripts that interact with GitLab Repositories (Generating Merge Requests, Pushing Commits/Tags, etc)
  - local: 'Automation/Repository.yml'
  # YML Scripts that interact with Documentation Tools (Confluence, GitLab Wiki, etc)
  - local: 'Automation/Documentation.yml'