tagCreation:
  before_script:
    - apk update
    - apk add git
    - rm -rf KnowledgeUniverse
  script:
    - Repo="KnowledgeUniverse"
    - Group="risk-engineering"
    - URL="https://$ServiceAcctTokenUsername:$ServiceAcctTokenKey@gitlab.ins.risk.regn.net/$Group/$Repo.git"
    - git --version
    - git clone --depth 1 $URL
    - git remote rm origin
    - git remote add origin $URL
    - TagDate=$(date +"%Y%m%d")
    - TagName="master_$TagDate"
    - echo "Tag Being Created - $TagName"
    - git tag $TagName
    - git push origin $TagName
  only:
    - schedules
  tags:
    - boca
    - docker
    - linux
    - privileged