#workunit('name', 'Testing_CLUE_Auto_StateFarm');
#option('expandSelectCreateRow', true); // Added to improve overall compile time

IMPORT KELBlackBox, KELGlobal, SALT35, SALTRoutines, UT;

MaxResults := 250; // The maximum number of records to show in the workunit

TransactionIDs := DATASET([{2951}], {UNSIGNED TransactionID}); // 2 unit recaps  1 inquiry recap

StateFarmKELResults := KELGlobal.S_C_L_U_E_Auto_State_Farm.Result(UID = TransactionIDs[1].TransactionID);
OUTPUT(CHOOSEN(StateFarmKELResults, MaxResults), NAMED('CLUEAutoStateFarm_KEL_Results'));

/* Debugging Queries - Raw File Results */
OUTPUT(CHOOSEN(KELBlackBox.FileCLUECleaned.FileCLUEAutoCleaned(RecordIdentifier = TransactionIDs[1].TransactionID), MaxResults), NAMED('RawAuto'));
OUTPUT(CHOOSEN(KELBlackBox.FileCLUECleaned.FileCLUEAutoSubjectID(RecordIdentifier = TransactionIDs[1].TransactionID), MaxResults), NAMED('RawAutoSubjectID'));
OUTPUT(CHOOSEN(KELBlackBox.FileCLUECleaned.FileCLUEAutoClaim(RecordIdentifier = TransactionIDs[1].TransactionID), MaxResults), NAMED('RawAutoClaims'));
OUTPUT(CHOOSEN(KELBlackBox.FileCLUECleaned.FileCLUEAutoPayments(RecordIdentifier = TransactionIDs[1].TransactionID), MaxResults), NAMED('RawAutoClaimsPayments'));
OUTPUT(CHOOSEN(KELBlackBox.FileCLUECleaned.FileCLUEAutoUnitRecap(RecordIdentifier = TransactionIDs[1].TransactionID), MaxResults), NAMED('RawAutoUnitRecap'));

/* Debugging Queries - KEL Results (NOTE: You must set #OPTION(persist, 0) in ClaimsAuto.kel before uncommenting these to run all at once, otherwise pick one and run) */
// OUTPUT(CHOOSEN(KELGlobal.Q_C_L_U_E_Auto_Subject_I_D(TransactionIDs[1].TransactionID).Res0, MaxResults), NAMED('SubjectID'));
// OUTPUT(CHOOSEN(KELGlobal.Q_C_L_U_E_Auto_Claim(TransactionIDs[1].TransactionID).Res0, MaxResults), NAMED('Claim'));
// OUTPUT(CHOOSEN(KELGlobal.Q_C_L_U_E_Auto_Recap(TransactionIDs[1].TransactionID).Res0, MaxResults), NAMED('Recap'));

StateFarmLayout := RECORD
	UNSIGNED8 TransactionID;
    INTEGER ACLE1001;
    INTEGER ACLE1002;
    INTEGER ACLE1003;
    INTEGER ACLE1004;
    INTEGER ACLE1005;
    INTEGER AFCLM45;
    INTEGER AFGE10K1;
    INTEGER AFGE10K2;
    INTEGER AFGE10K3;
    INTEGER AFGE10K4;
    INTEGER AFGE10K5;
    INTEGER AFGE15H1;
    INTEGER AFGE15H2;
    INTEGER AFGE15H3;
    INTEGER AFGE15H4;
    INTEGER AFGE15H5;
    INTEGER AFGE1K1;
    INTEGER AFGE1K2;
    INTEGER AFGE1K3;
    INTEGER AFGE1K4;
    INTEGER AFGE1K5;
    INTEGER AFGE5K1;
    INTEGER AFGE5K2;
    INTEGER AFGE5K3;
    INTEGER AFGE5K4;
    INTEGER AFGE5K5;
    INTEGER AFGE7501;
    INTEGER AFGE7502;
    INTEGER AFGE7503;
    INTEGER AFGE7504;
    INTEGER AFGE7505;
    INTEGER ALLGM1;
    INTEGER ALLGM2;
    INTEGER ALLGM3;
    INTEGER ALLGM4;
    INTEGER ALLGM5;
    INTEGER ALLRR1;
    INTEGER ALLRR2;
    INTEGER ALLRR3;
    INTEGER ALLRR4;
    INTEGER ALLRR5;
    INTEGER ATFGM1;
    INTEGER ATFGM2;
    INTEGER ATFGM3;
    INTEGER ATFGM4;
    INTEGER ATFGM5;
    INTEGER ATFRR1;
    INTEGER ATFRR2;
    INTEGER ATFRR3;
    INTEGER ATFRR4;
    INTEGER ATFRR5;
    INTEGER BI_CNT1NZ;
    INTEGER BI_CNT2NZ;
    INTEGER BI_CNT3NZ;
    INTEGER BI_CNT4NZ;
    INTEGER BI_CNT5NZ;
    INTEGER CLMS1NZ;
    INTEGER CLMS2NZ;
    INTEGER CLMS3NZ;
    INTEGER CLMS4NZ;
    INTEGER CLMS6NZ;
    INTEGER CLMS7NZ;
    INTEGER CO_CNT1NZ;
    INTEGER CO_CNT2NZ;
    INTEGER CO_CNT3NZ;
    INTEGER CO_CNT4NZ;
    INTEGER CO_CNT5NZ;
    INTEGER CP_CNT1NZ;
    INTEGER CP_CNT2NZ;
    INTEGER CP_CNT3NZ;
    INTEGER CP_CNT4NZ;
    INTEGER CP_CNT5NZ;
    INTEGER CPONLYCNT1;
    INTEGER CPONLYCNT2;
    INTEGER CPONLYCNT3;
    INTEGER CPONLYCNT4;
    INTEGER CPONLYCNT5;
    INTEGER GM_CNT1NZ;
    INTEGER GM_CNT2NZ;
    INTEGER GM_CNT3NZ;
    INTEGER GM_CNT4NZ;
    INTEGER GM_CNT5NZ;
    INTEGER MAJCPRV1;
    INTEGER MAJCPRV2;
    INTEGER MAJCPRV3;
    INTEGER MAJCPRV4;
    INTEGER MAJCPRV5;
    INTEGER MAJGE10K1;
    INTEGER MAJGE10K2;
    INTEGER MAJGE10K3;
    INTEGER MAJGE10K4;
    INTEGER MAJGE10K5;
    INTEGER MINCBPV1;
    INTEGER MINCBPV2;
    INTEGER MINCBPV3;
    INTEGER MINCBPV4;
    INTEGER MINCBPV5;
    INTEGER MINCCPV1;
    INTEGER MINCCPV2;
    INTEGER MINCCPV3;
    INTEGER MINCCPV4;
    INTEGER MINCCPV5;
    INTEGER MOSINCAF;
    INTEGER MOSINCE;
    INTEGER PD_CNT1NZ;
    INTEGER PD_CNT2NZ;
    INTEGER PD_CNT3NZ;
    INTEGER PD_CNT4NZ;
    INTEGER PD_CNT5NZ;
    INTEGER PDNOCO1;
    INTEGER PDNOCO2;
    INTEGER PDNOCO3;
    INTEGER PDNOCO4;
    INTEGER PDNOCO5;
    INTEGER RR_CNT1NZ;
    INTEGER RR_CNT2NZ;
    INTEGER RR_CNT3NZ;
    INTEGER RR_CNT4NZ;
    INTEGER RR_CNT5NZ;
    INTEGER SINGAC01;
    INTEGER SINGAC02;
    INTEGER SINGAC03;
    INTEGER SINGAC04;
    INTEGER SINGAC05;
    INTEGER TL_CNT1NZ;
    INTEGER TL_CNT2NZ;
    INTEGER TL_CNT3NZ;
    INTEGER TL_CNT4NZ;
    INTEGER TL_CNT5NZ;
    INTEGER TLONLYCNT1;
    INTEGER TLONLYCNT2;
    INTEGER TLONLYCNT3;
    INTEGER TLONLYCNT4;
    INTEGER TLONLYCNT5;
    INTEGER TOT_ATFAULT1NZ;
    INTEGER TOT_ATFAULT2NZ;
    INTEGER TOT_ATFAULT4NZ;
    INTEGER TOT_ATFAULT6NZ;
    INTEGER TOT_ATFAULT7NZ;
END;

StateFarmLayout CleanAttributeNames(RECORDOF(StateFarmKELResults) le) := TRANSFORM
	SELF.TransactionID := le.UID;
	SELF.ACLE1001 := le.Num_Accidents_L_E100_Within1_Yr_;
	SELF.ACLE1002 := le.Num_Accidents_L_E100_Within2_Yr_;
	SELF.ACLE1003 := le.Num_Accidents_L_E100_Within3_Yr_;
	SELF.ACLE1004 := le.Num_Accidents_L_E100_Within4_Yr_;
	SELF.ACLE1005 := le.Num_Accidents_L_E100_Within5_Yr_;
	SELF.AFCLM45 := le.Num_At_Fault_Clm_From3_Yr_To5_Yr_;
	SELF.AFGE10K1 := le.Num_At_Fault_Clm_G_E10000_Within1_Yr_;
	SELF.AFGE10K2 := le.Num_At_Fault_Clm_G_E10000_Within2_Yr_;
	SELF.AFGE10K3 := le.Num_At_Fault_Clm_G_E10000_Within3_Yr_;
	SELF.AFGE10K4 := le.Num_At_Fault_Clm_G_E10000_Within4_Yr_;
	SELF.AFGE10K5 := le.Num_At_Fault_Clm_G_E10000_Within5_Yr_;
	SELF.AFGE15H1 := le.Num_At_Fault_Clm_G_E1500_Within1_Yr_;
	SELF.AFGE15H2 := le.Num_At_Fault_Clm_G_E1500_Within2_Yr_;
	SELF.AFGE15H3 := le.Num_At_Fault_Clm_G_E1500_Within3_Yr_;
	SELF.AFGE15H4 := le.Num_At_Fault_Clm_G_E1500_Within4_Yr_;
	SELF.AFGE15H5 := le.Num_At_Fault_Clm_G_E1500_Within5_Yr_;
	SELF.AFGE1K1 := le.Num_At_Fault_Clm_G_E1000_Within1_Yr_;
	SELF.AFGE1K2 := le.Num_At_Fault_Clm_G_E1000_Within2_Yr_;
	SELF.AFGE1K3 := le.Num_At_Fault_Clm_G_E1000_Within3_Yr_;
	SELF.AFGE1K4 := le.Num_At_Fault_Clm_G_E1000_Within4_Yr_;
	SELF.AFGE1K5 := le.Num_At_Fault_Clm_G_E1000_Within5_Yr_;
	SELF.AFGE5K1 := le.Num_At_Fault_Clm_G_E5000_Within1_Yr_;
	SELF.AFGE5K2 := le.Num_At_Fault_Clm_G_E5000_Within2_Yr_;
	SELF.AFGE5K3 := le.Num_At_Fault_Clm_G_E5000_Within3_Yr_;
	SELF.AFGE5K4 := le.Num_At_Fault_Clm_G_E5000_Within4_Yr_;
	SELF.AFGE5K5 := le.Num_At_Fault_Clm_G_E5000_Within5_Yr_;
	SELF.AFGE7501 := le.Num_At_Fault_Clm_G_E750_Within1_Yr_;
	SELF.AFGE7502 := le.Num_At_Fault_Clm_G_E750_Within2_Yr_;
	SELF.AFGE7503 := le.Num_At_Fault_Clm_G_E750_Within3_Yr_;
	SELF.AFGE7504 := le.Num_At_Fault_Clm_G_E750_Within4_Yr_;
	SELF.AFGE7505 := le.Num_At_Fault_Clm_G_E750_Within5_Yr_;
	SELF.ALLGM1 := le.Num_N_Z_Gen_Med_Clm_Within1_Yr_;
	SELF.ALLGM2 := le.Num_N_Z_Gen_Med_Clm_Within2_Yr_;
	SELF.ALLGM3 := le.Num_N_Z_Gen_Med_Clm_Within3_Yr_;
	SELF.ALLGM4 := le.Num_N_Z_Gen_Med_Clm_Within4_Yr_;
	SELF.ALLGM5 := le.Num_N_Z_Gen_Med_Clm_Within5_Yr_;
	SELF.ALLRR1 := le.Num_N_Z_Rental_Reimb_Clm_Within1_Yr_;
	SELF.ALLRR2 := le.Num_N_Z_Rental_Reimb_Clm_Within2_Yr_;
	SELF.ALLRR3 := le.Num_N_Z_Rental_Reimb_Clm_Within3_Yr_;
	SELF.ALLRR4 := le.Num_N_Z_Rental_Reimb_Clm_Within4_Yr_;
	SELF.ALLRR5 := le.Num_N_Z_Rental_Reimb_Clm_Within5_Yr_;
	SELF.ATFGM1 := le.Num_At_Fault_N_Z_Gen_Med_Clm_Within1_Yr_;
	SELF.ATFGM2 := le.Num_At_Fault_N_Z_Gen_Med_Clm_Within2_Yr_;
	SELF.ATFGM3 := le.Num_At_Fault_N_Z_Gen_Med_Clm_Within3_Yr_;
	SELF.ATFGM4 := le.Num_At_Fault_N_Z_Gen_Med_Clm_Within4_Yr_;
	SELF.ATFGM5 := le.Num_At_Fault_N_Z_Gen_Med_Clm_Within5_Yr_;
	SELF.ATFRR1 := le.Num_At_Fault_N_Z_Rental_Reimb_Clm_Within1_Yr_;
	SELF.ATFRR2 := le.Num_At_Fault_N_Z_Rental_Reimb_Clm_Within2_Yr_;
	SELF.ATFRR3 := le.Num_At_Fault_N_Z_Rental_Reimb_Clm_Within3_Yr_;
	SELF.ATFRR4 := le.Num_At_Fault_N_Z_Rental_Reimb_Clm_Within4_Yr_;
	SELF.ATFRR5 := le.Num_At_Fault_N_Z_Rental_Reimb_Clm_Within5_Yr_;
	SELF.BI_CNT1NZ := le.Num_N_Z_Bodily_Inj_Cpnt_Within1_Yr_;
	SELF.BI_CNT2NZ := le.Num_N_Z_Bodily_Inj_Cpnt_Within2_Yr_;
	SELF.BI_CNT3NZ := le.Num_N_Z_Bodily_Inj_Cpnt_Within3_Yr_;
	SELF.BI_CNT4NZ := le.Num_N_Z_Bodily_Inj_Cpnt_Within4_Yr_;
	SELF.BI_CNT5NZ := le.Num_N_Z_Bodily_Inj_Cpnt_Within5_Yr_;
	SELF.CLMS1NZ := le.Num_N_Z_Clm_Within1_Yr_;
	SELF.CLMS2NZ := le.Num_N_Z_Clm_Within2_Yr_;
	SELF.CLMS3NZ := le.Num_N_Z_Clm_Within3_Yr_;
	SELF.CLMS4NZ := le.Num_N_Z_Clm_Within4_Yr_;
	SELF.CLMS6NZ := le.Num_N_Z_Clm_Within6_Yr_;
	SELF.CLMS7NZ := le.Num_N_Z_Clm_Within7_Yr_;
	SELF.CO_CNT1NZ := le.Num_N_Z_Coll_Cpnt_Within1_Yr_;
	SELF.CO_CNT2NZ := le.Num_N_Z_Coll_Cpnt_Within2_Yr_;
	SELF.CO_CNT3NZ := le.Num_N_Z_Coll_Cpnt_Within3_Yr_;
	SELF.CO_CNT4NZ := le.Num_N_Z_Coll_Cpnt_Within4_Yr_;
	SELF.CO_CNT5NZ := le.Num_N_Z_Coll_Cpnt_Within5_Yr_;
	SELF.CP_CNT1NZ := le.Num_N_Z_Comp_Cpnt_Within1_Yr_;
	SELF.CP_CNT2NZ := le.Num_N_Z_Comp_Cpnt_Within2_Yr_;
	SELF.CP_CNT3NZ := le.Num_N_Z_Comp_Cpnt_Within3_Yr_;
	SELF.CP_CNT4NZ := le.Num_N_Z_Comp_Cpnt_Within4_Yr_;
	SELF.CP_CNT5NZ := le.Num_N_Z_Comp_Cpnt_Within5_Yr_;
	SELF.CPONLYCNT1 := le.Num_N_Z_Comp_Only_Clm_Within1_Yr_;
	SELF.CPONLYCNT2 := le.Num_N_Z_Comp_Only_Clm_Within2_Yr_;
	SELF.CPONLYCNT3 := le.Num_N_Z_Comp_Only_Clm_Within3_Yr_;
	SELF.CPONLYCNT4 := le.Num_N_Z_Comp_Only_Clm_Within4_Yr_;
	SELF.CPONLYCNT5 := le.Num_N_Z_Comp_Only_Clm_Within5_Yr_;
	SELF.GM_CNT1NZ := le.Num_N_Z_Gen_Med_Cpnt_Within1_Yr_;
	SELF.GM_CNT2NZ := le.Num_N_Z_Gen_Med_Cpnt_Within2_Yr_;
	SELF.GM_CNT3NZ := le.Num_N_Z_Gen_Med_Cpnt_Within3_Yr_;
	SELF.GM_CNT4NZ := le.Num_N_Z_Gen_Med_Cpnt_Within4_Yr_;
	SELF.GM_CNT5NZ := le.Num_N_Z_Gen_Med_Cpnt_Within5_Yr_;
	SELF.MAJCPRV1 := le.Num_Clm_G_E5000_Within1_Yr_;
	SELF.MAJCPRV2 := le.Num_Clm_G_E5000_Within2_Yr_;
	SELF.MAJCPRV3 := le.Num_Clm_G_E5000_Within3_Yr_;
	SELF.MAJCPRV4 := le.Num_Clm_G_E5000_Within4_Yr_;
	SELF.MAJCPRV5 := le.Num_Clm_G_E5000_Within5_Yr_;
	SELF.MAJGE10K1 := le.Num_Clm_G_E10000_Within1_Yr_;
	SELF.MAJGE10K2 := le.Num_Clm_G_E10000_Within2_Yr_;
	SELF.MAJGE10K3 := le.Num_Clm_G_E10000_Within3_Yr_;
	SELF.MAJGE10K4 := le.Num_Clm_G_E10000_Within4_Yr_;
	SELF.MAJGE10K5 := le.Num_Clm_G_E10000_Within5_Yr_;
	SELF.MINCBPV1 := le.Num_N_Z_Clm_L_E100_No_Tow_Labor_Pmt_Within1_Yr_;
	SELF.MINCBPV2 := le.Num_N_Z_Clm_L_E100_No_Tow_Labor_Pmt_Within2_Yr_;
	SELF.MINCBPV3 := le.Num_N_Z_Clm_L_E100_No_Tow_Labor_Pmt_Within3_Yr_;
	SELF.MINCBPV4 := le.Num_N_Z_Clm_L_E100_No_Tow_Labor_Pmt_Within4_Yr_;
	SELF.MINCBPV5 := le.Num_N_Z_Clm_L_E100_No_Tow_Labor_Pmt_Within5_Yr_;
	SELF.MINCCPV1 := le.Num_N_Z_Clm_L_E100_Within1_Yr_;
	SELF.MINCCPV2 := le.Num_N_Z_Clm_L_E100_Within2_Yr_;
	SELF.MINCCPV3 := le.Num_N_Z_Clm_L_E100_Within3_Yr_;
	SELF.MINCCPV4 := le.Num_N_Z_Clm_L_E100_Within4_Yr_;
	SELF.MINCCPV5 := le.Num_N_Z_Clm_L_E100_Within5_Yr_;
	SELF.MOSINCAF := le.Num_Mos_Since_Last_At_Fault_Clm_;
	SELF.MOSINCE := le.Num_Mos_Since_Last_Clm_;
	SELF.PD_CNT1NZ := le.Num_N_Z_Prop_Dam_Cpnt_Within1_Yr_;
	SELF.PD_CNT2NZ := le.Num_N_Z_Prop_Dam_Cpnt_Within2_Yr_;
	SELF.PD_CNT3NZ := le.Num_N_Z_Prop_Dam_Cpnt_Within3_Yr_;
	SELF.PD_CNT4NZ := le.Num_N_Z_Prop_Dam_Cpnt_Within4_Yr_;
	SELF.PD_CNT5NZ := le.Num_N_Z_Prop_Dam_Cpnt_Within5_Yr_;
	SELF.PDNOCO1 := le.Num_Prop_Dam_G_T1000_No_Coll_Pmt_Within1_Yr_;
	SELF.PDNOCO2 := le.Num_Prop_Dam_G_T1000_No_Coll_Pmt_Within2_Yr_;
	SELF.PDNOCO3 := le.Num_Prop_Dam_G_T1000_No_Coll_Pmt_Within3_Yr_;
	SELF.PDNOCO4 := le.Num_Prop_Dam_G_T1000_No_Coll_Pmt_Within4_Yr_;
	SELF.PDNOCO5 := le.Num_Prop_Dam_G_T1000_No_Coll_Pmt_Within5_Yr_;
	SELF.RR_CNT1NZ := le.Num_N_Z_Rental_Reimb_Cpnt_Within1_Yr_;
	SELF.RR_CNT2NZ := le.Num_N_Z_Rental_Reimb_Cpnt_Within2_Yr_;
	SELF.RR_CNT3NZ := le.Num_N_Z_Rental_Reimb_Cpnt_Within3_Yr_;
	SELF.RR_CNT4NZ := le.Num_N_Z_Rental_Reimb_Cpnt_Within4_Yr_;
	SELF.RR_CNT5NZ := le.Num_N_Z_Rental_Reimb_Cpnt_Within5_Yr_;
	SELF.SINGAC01 := le.Num_Sing_Car_Acc_Clm_Within1_Yr_;
	SELF.SINGAC02 := le.Num_Sing_Car_Acc_Clm_Within2_Yr_;
	SELF.SINGAC03 := le.Num_Sing_Car_Acc_Clm_Within3_Yr_;
	SELF.SINGAC04 := le.Num_Sing_Car_Acc_Clm_Within4_Yr_;
	SELF.SINGAC05 := le.Num_Sing_Car_Acc_Clm_Within5_Yr_;
	SELF.TL_CNT1NZ := le.Num_N_Z_Tow_Labor_Cpnt_Within1_Yr_;
	SELF.TL_CNT2NZ := le.Num_N_Z_Tow_Labor_Cpnt_Within2_Yr_;
	SELF.TL_CNT3NZ := le.Num_N_Z_Tow_Labor_Cpnt_Within3_Yr_;
	SELF.TL_CNT4NZ := le.Num_N_Z_Tow_Labor_Cpnt_Within4_Yr_;
	SELF.TL_CNT5NZ := le.Num_N_Z_Tow_Labor_Cpnt_Within5_Yr_;
	SELF.TLONLYCNT1 := le.Num_N_Z_Tow_Labor_Only_Clm_Within1_Yr_;
	SELF.TLONLYCNT2 := le.Num_N_Z_Tow_Labor_Only_Clm_Within2_Yr_;
	SELF.TLONLYCNT3 := le.Num_N_Z_Tow_Labor_Only_Clm_Within3_Yr_;
	SELF.TLONLYCNT4 := le.Num_N_Z_Tow_Labor_Only_Clm_Within4_Yr_;
	SELF.TLONLYCNT5 := le.Num_N_Z_Tow_Labor_Only_Clm_Within5_Yr_;
	SELF.TOT_ATFAULT1NZ := le.Num_N_Z_At_Fault_Clm_Within1_Yr_;
	SELF.TOT_ATFAULT2NZ := le.Num_N_Z_At_Fault_Clm_Within2_Yr_;
	SELF.TOT_ATFAULT4NZ := le.Num_N_Z_At_Fault_Clm_Within4_Yr_;
	SELF.TOT_ATFAULT6NZ := le.Num_N_Z_At_Fault_Clm_Within6_Yr_;
	SELF.TOT_ATFAULT7NZ := le.Num_N_Z_At_Fault_Clm_Within7_Yr_;
END;

FinalStateFarmAttributes := PROJECT(StateFarmKELResults, CleanAttributeNames(LEFT));
OUTPUT(CHOOSEN(FinalStateFarmAttributes, MaxResults), NAMED('CLUEAutoStateFarm_Final_Results'));