name: 'KEL Workflow Setup'
description: 'Setup for a KEL Compiler Workflow'
author: Brenton Pahl

# -----------------------------------------------------------------------------
#  Standard KEL Workflow Setup
#  NOTE: This Workflow will likely also be run with the OpenJDK Workflow Setup
#  1. Read the kel.config file, parse out the KEL version
#  2. Download the appropriate KEL.jar version and rename to KEL.jar
#  3. Perform a quick KEL Version check
# -----------------------------------------------------------------------------

inputs:
  kel-config-location:
    description: 'Path to the kel.config file we should read to determine KEL Compiler Version'
    required: true
  jfrog-authentication-token:
    description: 'The JFrog API Token for accessing JFrog artifacts such as the KEL Compiler'
    required: true

runs:
  using: "composite"
  steps:
    # Step 1.) Read the kel.config file
    - name: Read kel.config Version Information
      id: read_kel_version
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: ${{ inputs.kel-config-location }}
        property: 'kel.version'
    # Step 2.) Download KEL.jar
    - name: Download KEL Compiler
      id: download_kel_compiler
      uses: advancedcsg-open/action-jfrog-cli@v1.2.0
      with:
        url: 'https://useast.jfrog.lexisnexisrisk.com'
        credentials type: 'accesstoken'
        access token: ${{ inputs.jfrog-authentication-token }}
        args: download "glb-maven-snapshot-virtual/com/relx/rba/tardis/kel/${{ steps.read_kel_version.outputs.value }}/*-jar-with-dependencies.jar" "KEL.jar" --sort-by=created --sort-order=desc --flat=true --limit=1
    # Step 3.) Output the KEL version
    - name: KEL Compiler Version Check
      continue-on-error: true
      run: java -jar KEL.jar --version
      shell: bash
