name: 'HPCC Submit Workunit'
description: 'Submits a workunit to HPCC'
author: Brenton Pahl

# -----------------------------------------------------------------------------
#  This action uses ecl/eclcc to submit workunits to an HPCC environment
# NOTE: The hpcc-workflow-setup is a prerequisite for this to work
# and this action assumes running with image: useast.jfrog.lexisnexisrisk.com/hpccpl-docker-nonprod-local/platform-core-ln:latest
# -----------------------------------------------------------------------------

inputs:
  raw-ecl-code:
    description: 'Raw/In-Line ECL Code to submit'
    required: false
  ecl-code:
    description: 'Full path to the ECL code to submit'
    required: false
  ecl-watch-url:
    description: 'URL to submit to'
    required: false
    default: 'alpha_vault_thor_esp.risk.regn.net'
  ecl-watch-port:
    description: 'Port number to submit to. Concat with ecl-watch-url'
    required: false
    default: '18010'
  hpcc-username:
    description: 'HPCC Username to submit with'
    required: true
  hpcc-password:
    description: 'HPCC Password to submit with'
    required: true
  hpcc-target:
    description: 'Name of the HPCC Target to submit to, such as hthor'
    required: true
  workunit-name:
    description: 'Name to give the workunit being submitted'
    required: false
  syntax-only:
    description: 'Dont run the job, just syntax check'
    type: boolean
    default: false
    required: false
  

runs:
  using: "composite"
  steps:
    - name: Syntax Check
      # If we are not running inside a pull request, pull the main branch with a depth of 1
      if: ${{ inputs.syntax-only == true }} && ${{ inputs.raw-ecl-code == '' }}
      run: |
        eclcc -syntax -legacy -v -platform=thor -I ${{ env.GITHUB_WORKSPACE }} ${{ format('{0}/{1}', env.GITHUB_WORKSPACE, inputs.ecl-code) }}
      shell: bash
    - name: Compile and Run
      # If we are not running inside a pull request, pull the main branch with a depth of 1
      if: ${{ inputs.syntax-only == false }} && ${{ inputs.raw-ecl-code == '' }}
      run: |
        ecl run ${{ inputs.hpcc-target }} --server=${{ inputs.ecl-watch-url }} --port=${{ inputs.ecl-watch-port }} --ssl --username=${{ inputs.hpcc-username }} --password=${{ inputs.hpcc-password }} -legacy -v -I ${{ env.GITHUB_WORKSPACE }} --job-name=${{ inputs.workunit-name }} --input=${{ format('{0}/{1}', env.GITHUB_WORKSPACE, inputs.ecl-code) }}
      shell: bash
    - name: Compile and Run - Inline ECL
      # If we are not running inside a pull request, pull the main branch with a depth of 1
      if: ${{ inputs.syntax-only == false }} && ${{ inputs.raw-ecl-code != '' }}
      run: |
        ecl run ${{ inputs.hpcc-target }} --server=${{ inputs.ecl-watch-url }} --port=${{ inputs.ecl-watch-port }} --ssl --username=${{ inputs.hpcc-username }} --password=${{ inputs.hpcc-password }} -legacy -v -I ${{ env.GITHUB_WORKSPACE }} --job-name=${{ inputs.workunit-name }} --input=${{ inputs.raw-ecl-code }}
      shell: bash