EXPORT Source := project(I_Bankruptcy_Search.Constants.Sourcefile, transform(I_Bankruptcy_Search.Layout_Vault, 
   																																								SELF.vault_date_first_seen := (UNSIGNED4)WORKUNIT[2..9];
   																																								SELF.vault_date_last_seen := 	0;
   																																								SELF.vault_rid := 	0;
																																									SELF.vault_UID_Hash := HASH64(left.process_date,left.caseid,left.defendantid,left.recid,left.tmsid,left.seq_number,left.court_code,left.case_number,left.orig_case_number,left.chapter,left.filing_type,left.business_flag,left.corp_flag,left.discharged,left.disposition,left.pro_se_ind,left.converted_date,left.orig_county,left.debtor_type,left.debtor_seq,left.ssn,left.ssnsrc,left.ssnmatch,left.ssnmsrc,left.screen,left.dcode,left.disptype,left.dispreason,left.statusdate,left.holdcase,left.datevacated,left.datetransferred,left.activityreceipt,left.tax_id,left.name_type,left.orig_name,left.orig_fname,left.orig_mname,left.orig_lname,left.orig_name_suffix,left.title,left.fname,left.mname,left.lname,left.name_suffix,left.name_score,left.cname,left.orig_company,left.orig_addr1,left.orig_addr2,left.orig_city,left.orig_st,left.orig_zip5,left.orig_zip4,left.orig_email,left.orig_fax,left.prim_range,left.predir,left.prim_name,left.addr_suffix,left.postdir,left.unit_desig,left.sec_range,left.p_city_name,left.v_city_name,left.st,left.zip,left.zip4,left.cart,left.cr_sort_sz,left.lot,left.lot_order,left.dbpc,left.chk_digit,left.rec_type,left.county,left.geo_lat,left.geo_long,left.msa,left.geo_blk,left.geo_match,left.err_stat,left.phone,left.did,left.bdid,left.app_ssn,left.app_tax_id,left.date_first_seen,left.date_last_seen,left.date_vendor_first_reported,left.date_vendor_last_reported,left.disptypedesc,left.srcdesc,left.srcmtchdesc,left.screendesc,left.dcodedesc,left.date_filed,left.record_type,left.delete_flag,left.dotid,left.dotscore,left.dotweight,left.empid,left.empscore,left.empweight,left.powid,left.powscore,left.powweight,left.proxid,left.proxscore,left.proxweight,left.seleid,left.selescore,left.seleweight,left.orgid,left.orgscore,left.orgweight,left.ultid,left.ultscore,left.ultweight,left.source_rec_id,left.scrubsbits1
);
   																																								SELF := LEFT;
   																																								SELF:=[];
   																																								));
																																									